### ISSUE TITLE
Set case formatting within code

### ISSUE THREAD

**Issue by ruudvanham** [yuanhjty/code-template-tool#8]
Our folder and css class naming is kebabCase and we would like our naming in JS to be camelCase.
Also we're using `.c_[component-name]` as our css naming convention. Only way to get this to work is to add a prefix to an extra variable. Because when I use `.c____var___ {}` inside the template all underscores are replaced. even the additional first .c**_**
 
We can add multiple (3) vars to accomplish this but I was wondering if you could support case formatting inside templates and only replace three underscores before the var. So depending of the template we could convert the variable to a preferred case and can use an underscore before a var name. This way we can use a single var to accomplish all above.

**Comment by yuanhjty** [comment]
@ruudvanham  The issue that the additional underscores are replaced will be fixed in the next version(0.4.0).

In addition, taking `___` as variable's boundaries seems to be an ill-considered decision. 
So the next version(0.4.0) will support customizing variable's left boundary and right boundary via the `codeTemplateTool.variable.leftBoundary` and `codeTemplateTool.variable.rightBoundary` fields in user settings.
For example, with the following settings
```json
{
    "codeTemplateTool.variable.leftBoundary": "{_",
    "codeTemplateTool.variable.rightBoundary": "_}",
}
```
a variable will be like this `{_var_}`.
